#!/usr/bin/env python2

from sys import argv

with open(argv[1], "r+") as wrapper:
    with open(argv[2], "r") as content:
        wrapper_data = wrapper.read()
        wrapper_data = wrapper_data.replace("---MARKDOWN GOES HERE---", content.read())
        wrapper.seek(0)
        wrapper.write(wrapper_data)
        wrapper.truncate()

