#!/bin/bash

./compile_tutorial ../tutorials/understanding-vpns
./compile_tutorial ../tutorials/choosing-a-vpn
./compile_tutorial ../tutorials/understanding-cryptography
./compile_tutorial ../tutorials/password-managers
./compile_tutorial ../tutorials/threat-models