#!/bin/bash

./markdown2 "$@".md > "$@".content.uncorrected.html
./html_corrector "$@".content.uncorrected.html > "$@".content.html
./combine "$@".html "$@".content.html
rm "$@".content.uncorrected.html "$@".content.html