#!/usr/bin/env python3

from sys import argv
from bs4 import BeautifulSoup

with open(argv[1], 'r') as i:
    data = i.read()
    data = data.replace("<h2>", "<h2 class=\"section-heading\">")
    data = data.replace("<table>", "<table class=\"table table-striped table-bordered\">")

    soup = BeautifulSoup(data, "html.parser")

    blockquotes = soup.findAll("blockquote")
    new_blockquotes = []
    for blockquote in blockquotes:
        if blockquote.find("p"):
            blockquote.p.replaceWithChildren()

    print(str(soup))
